name: Build and Test Kalah

on:
  push:
    branches:
      - submission
jobs:
  build:
    name: Run make with target tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
             distribution: zulu
             java-version: 7.0.342+1
      - run: make tests
